### ISSUE TITLE
Lots of sensors dissapeared with upgrade to 0.22.2

### ISSUE THREAD

**Issue by kodsama** [bosch-thermostat/home-assistant-bosch-custom-component#292] opened 2023-04-27 06:51 UTC
**Describe the bug**
I upgraded from 0.21.0 to 0.22.2 and a lot of sensors disapeared during the transition. I did check the new sensors available and renamed the ones I could match but those are just not available/updated anymore. Those were updating before the update.

Entities:
  - dhw1_water_flow
  - dhw1_working_time
  - current_summer_winter_mode
  - summer_winter_switchmode
  - summer_winter_threshold
  - actual_power
  - system_pressure

All these have been imported again but are always unavailable now:
  - recording_rcompressor
  - recording_rconsumedenergy
  - recording_reheater
  - recording_routputproduced
  - recording_rroomtemperature

The most bothering are the recording sensors and summer_winter modes as I can't track heatpump usage anymore.

**To Reproduce**
Upgrade to 0.22

**Expected behavior**
Re-introduce missing sensors

**Screenshots**

**Version**
  - HA version: 2023.4.6
  - HA Bosch component version? 0.22.2

** Debug SCAN **
** IMPORTANT **
How do I pull UUID?

**Comment by kodsama** [comment] 2023-04-27 07:59
Just FYI, 
I recreated the recording_rroomtemperature by using a template:
`sensor:
  - platform: template
    sensors:
      ivt_room_setpoint:
        value_template: "{{ states.climate.hc1.attributes['temperature'] | float }}"
        unit_of_measurement: '°C'
        friendly_name: 'IVT Room Temperature Setpoint'`

**Comment by clemenslermen** [comment] 2023-05-04 10:54
Have the same problem ... for me it is "sensor.gas_spent" which is now completely missing. Any hint where to find it?

**Comment by kodsama** [comment] 2023-05-24 06:19
I haven't found the deprecated code yet.
sensor.recording_ractualpower also dissapeared on my side.

**Comment by mans-se** [comment] 2023-05-24 19:16
The recording sensors stopped working for me as well on a Bosch Compress 3800i a month ago or so.

**Comment by kodsama** [comment] 2023-06-13 20:21
This might be related to #289

**Comment by pszafer** [comment] 2023-07-10 19:41
can you try version v0.22.3dev1?
You'd need to enable `Use new statistic API` in integration option once again.

**Comment by pszafer** [comment] 2023-07-19 10:51
This is duplicate of https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/issues/289. Let's close this one.

**Closed by pszafer** 2023-07-19 10:51 UTC
