### ISSUE TITLE
Unknown Model

### ISSUE THREAD

**Issue by the-baumis** [bosch-thermostat/home-assistant-bosch-custom-component#400] opened 2024-04-05 14:03 UTC
**Describe the bug**
Connect Bosch Compress 7000i AW - Unknown Model

**Expected behavior**
I tried to connect my Bosch Compress 7100i aw 13 to Home Assistant.
The system has a Bosch Connect-Key K 30 RF module

**Screenshots**

![image](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/assets/124595847/f7134175-dd4a-4592-8104-a6efa358ae8b)

**Version**
  - HA version = 2024.4.0
  - HA Bosch component version = v.0.25.0

** Debug SCAN **

This error was caused by a custom integration

Logger: custom_components.bosch
Quelle: custom_components/bosch/__init__.py:305
Integration: Bosch thermostat (Dokumentation, Probleme)
Erstmals aufgetreten: 15:41:55 (8 Vorkommnisse)
Zuletzt protokolliert: 15:56:04

Your device is unknown null

**Comment by jaronheskamp** [comment] 2024-04-05 14:09
+1

**Comment by EifelIvy** [comment] 2024-04-08 07:56
+1

**Comment by olyckne** [comment] 2024-04-08 08:51
That module isn't supported. People are trying to figure it out.
For example here: https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/issues/335

**Comment by sioh4** [comment] 2024-04-12 14:29
> That module isn't supported. People are trying to figure it out. For example here: #335

Hi @olyckne 
since latest two HA core updates the  BT integration delivers also for **RC200** "unknown model" with an error -> initialisation loop; before that it worked perfectly
any idea what can cause this conflict
THX

**Comment by olyckne** [comment] 2024-04-17 17:49
@sioh4 I'm not really involved in this project more than that I have K30 module and wants to use this integration with it so can't really help you unfortunately.

**Comment by UniCizin** [comment] 2024-04-29 12:51
same thing here. can we do anything to help/push/proceed here?

**Comment by pszafer** [comment] 2024-04-29 20:02
Duplicate of https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/issues/335

**Closed by pszafer** 2024-04-29 20:02 UTC
