### ISSUE TITLE
Add support for CT200

### ISSUE THREAD

**Issue by doudz** [bosch-thermostat/home-assistant-bosch-custom-component#64] opened 2021-04-12 19:20 UTC
Since the magic key has been discovered (thanks @robertklep ! 🎉 )
Could you add support for CT200 ?

all information could be found here : https://github.com/robertklep/bosch-xmpp/issues/4

**Comment by pszafer** [comment] 2021-04-12 19:31
I know about it. I've already started to figuring it out...

**Comment by doudz** [comment] 2021-04-12 19:47
I can help if needed

**Comment by pszafer** [comment] 2021-04-12 20:13
I'll try tomorrow to make branch with new encryption key, then I'll create new bosch_scan method and last step probably the hardest right now is to figure it all out to get similar scheme to this https://github.com/bosch-thermostat/bosch-thermostat-client-python/blob/dev/bosch_thermostat_client/db/rc300_rc200/040607.json

so yeah, any help will be appreciated! I'll let you know when there will be something to test

**Comment by robertklep** [comment] 2021-04-13 05:28
I can help too 👍🏻

**Comment by doudz** [comment] 2021-04-13 07:24
I have started to add support https://github.com/doudz/bosch-thermostat-client-python/tree/ct200

**Comment by doudz** [comment] 2021-04-13 09:39
Looks like /system/sensors/temperatures/indoorAirDigital report the wrong temperature
the correct one is /gateway/test/indoorAirDigitalCompensatedTemperature

**Comment by pszafer** [comment] 2021-04-13 11:26
I see that you've done a lot! cool.
Basically from what I see we need bosch scan made by lib, so I can rewrite http-simulator to support easy control and then we can test everything without connecting to bosch xmpp servers.

Also we need scan from somebody who has 2 heating circuits, I don't know how schedule is working if there are HC1 and HC2 together (maybe it is impossible with these Easycontrol?)

**Comment by pszafer** [comment] 2021-04-13 15:38
@doudz I'm waiting for PR from you.
Simulator now supports EASYCONTROL and NEFIT via HTTP:
to run simulator install v0.0.2 - https://pypi.org/project/bosch-thermostat-http-simulator/
```
bosch_simulator -f scans/nefit/1_scan.json --device NEFIT
```

Then with newest version of lib and master version of component you could choose nefit and put host "127.0.0.1:8080" as serial number and `bosch_simulator` will try to simulate nefit for you.
when I get first scans of EasyControl (after PR) I'd be able to simulate EasyControl as well.

**Comment by doudz** [comment] 2021-04-13 18:24
I'm not sure to understand what you need, do you want me to give you the raw_xxxxxx.json file made using bosch_cli scan command ?

**Comment by pszafer** [comment] 2021-04-13 18:35
PR with work you've already done and rawscan so I can work with you on this.

**Comment by pszafer** [comment] 2021-04-13 18:51
ok, my bad. I missed notification about PR in bosch lib. sorry. I will merge it tomorrow morning

**Comment by pszafer** [comment] 2021-04-14 16:20
can you provide new scan with fresh lib `pip install bosch-thermostat-client==0.12.0.dev2` ?
I added extra uri's to it and now it removes all confidential data (this device has your address, geo localization, name, email).

**Comment by doudz** [comment] 2021-04-14 16:34
New scan 
[rawscan_101027819.zip](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/6312368/rawscan_101027819.zip)

```
2021-04-14 18:32:17 INFO (MainThread) [__main__] Running scan
2021-04-14 18:32:17 INFO (MainThread) [__main__] Successfully connected to gateway. Found UUID: 101027819
2021-04-14 18:32:21 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] 400 HTTP Error - ['HTTP/1.1 405 Method Not Allowed', 'Seq-No: 50', 'Content-Length: 0', 'Content-Type: application/json', 'Connection: close', '', '']
2021-04-14 18:32:21 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /gateway/test/EEPROMvalues
2021-04-14 18:32:31 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] 400 HTTP Error - ['HTTP/1.1 404 Not Found', 'Seq-No: 178', 'Content-Length: 0', 'Content-Type: application/json', 'Connection: close', '', '']
2021-04-14 18:32:31 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /solarCircuits
2021-04-14 18:32:32 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] 400 HTTP Error - ['HTTP/1.1 404 Not Found', 'Seq-No: 179', 'Content-Length: 0', 'Content-Type: application/json', 'Connection: close', '', '']
2021-04-14 18:32:32 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /recordings
2021-04-14 18:32:33 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] 400 HTTP Error - ['HTTP/1.1 400 Bad Request', 'Seq-No: 194', 'Content-Length: 0', 'Content-Type: application/json', 'Connection: close', '', '']
2021-04-14 18:32:33 INFO (MainThread) [bosch_thermostat_client.connectors.xmpp] Msg exception for /devices/productLookup
2021-04-14 18:32:38 INFO (MainThread) [__main__] Successfully saved result to file: rawscan_101027819.json
```

**Comment by pszafer** [comment] 2021-04-14 16:43
I have scan from somebody else and here are my thoughts on this:
- I don't know what is `/heatingCircuits/hc1` now `/heatingCircuits/hc1/type => value: radiator`, I don't think we can use heatingCircuits as thermostat controller in HA,
- I think that temperature is controlled per room `/zones/znX`
  - `/zones/znX/name` - name of zone
  - `/zones/znX/temperatureActual` - current temperature in the room
  - `/zones/znX/status` -> status of heating, either `idle`, `heat request` or ....
  - `/zones/znX/userMode` -> operation mode `clock` or `manual`? (manual is a guess from nefit)
    - if usermode is **clock** then:
      - to set new temperature till next setpoint PUT to `/zones/znX/clockOverride/temperatureHeating`
      - schedule is visible in `/programs/pgY` -> here it is little weird, there is program for whole week and programs for each day.
        - for now I don't know how to recognize which pg is for which zone
    - if usermode is **manual** then:
      - to set new temperature use `/zones/znX/manualTemperatureHeating`

water_heater / dhw circuit seems like is much more like KM200.

**Comment by doudz** [comment] 2021-04-14 19:43
Your thoughts looks good

**Comment by pszafer** [comment] 2021-04-15 11:42
I think you can test it now:
![image](https://user-images.githubusercontent.com/690510/114863547-2695de80-9df0-11eb-8cdf-4592f4488d4d.png)

Although I don't understand yours `dhwCircuit`.
operation_mode is `high` so in older devices it meant that it won't follow schedule:
```
{
            "id": "/dhwCircuits/dhw1/operationMode",
            "type": "stringValue",
            "writeable": 1,
            "recordable": 0,
            "used": "true",
            "available": "true",
            "infoText": "",
            "value": "high"
        },
```
but temperature in high is **0** so either you have dhw disabled or ... no idea
```
{
            "id": "/dhwCircuits/dhw1/temperatureLevels/high",
            "type": "floatValue",
            "writeable": 1,
            "recordable": 0,
            "value": 0.0,
            "used": "false",
            "available": "false",
            "unitOfMeasure": "C",
            "minValue": 10.0,
            "maxValue": 80.0,
            "stepSize": 1.0
        },
```

**Comment by doudz** [comment] 2021-04-15 12:07
I can't have the latest master release from hacs, when I choose master, it install the release 0.11.4...

**Comment by doudz** [comment] 2021-04-15 12:12
Ok, I'll test it
thank you !

**Comment by doudz** [comment] 2021-04-15 13:29
I got the same TLS handshake problem
![image](https://user-images.githubusercontent.com/1262548/114877080-408aed80-9dff-11eb-96b7-c88f557ee058.png)

For information, I'm running HA core in venv on Rasbian Buster with manually compiled python3.8

**Comment by doudz** [comment] 2021-04-15 13:32
I think there's something missing in my venv but I don't know what
trying `python3 -m bosch_thermostat_client.bosch_cli query` command in the same venv produce the same error

**Comment by robertklep** [comment] 2021-04-15 13:33
@doudz likely this issue: https://github.com/robertklep/nefit-easy-http-server#problems-on-recent-linux-distributions

**Comment by pszafer** [comment] 2021-04-15 13:33
your python3.8 seems to be wrongly compiled. I had users with same errors and they followed this tutorial:
https://community.home-assistant.io/t/home-assistant-core-python-3-8-backport-for-debian-buster/234859

**Comment by doudz** [comment] 2021-04-15 13:35
@pszafer Following the tutorial solve the problem for other users ?

**Comment by pszafer** [comment] 2021-04-15 14:23
unfortunately I don't have much feedback after sharing it, but no more complains so I think it's good sign...
going back to encryption lib, I have feedback from one user that PUT is not working so I'm gonna remove one `\r`.

**Comment by doudz** [comment] 2021-04-15 17:56
ok thanks, I'm rebuilding my venv with this version of python 3.8

**Comment by pszafer** [comment] 2021-04-15 18:34
ok, I will push many fixes and improvements tomorrow

**Comment by doudz** [comment] 2021-04-15 19:45
Same problem for me...
[('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')]
I have to find why

**Comment by Didel** [comment] 2021-04-15 20:11
The current version (in the Master branch) works for me! Meaning, I am able to connect to the CT200 and (at least) read the desired and actual temperatures in Home Assistant! Thanks for the great work so far!

If there is anything I can do to help, let me know!

**Comment by doudz** [comment] 2021-04-16 06:55
Now it works with master branch but :
Missing base64 decoding of name `TGUgU8Opam91cg==` instead of `Le Séjour`
![image](https://user-images.githubusercontent.com/1262548/114981800-d6ba2480-9e8e-11eb-9efb-0ff23f086602.png)

/dhwCircuits/dhw1/operationMode could be :
- `Off` : no hot water production
- `high` : hot water production as soon as the tank is refilled
- `ownprogram` : automatic production mode, _economic mode_


Logger: homeassistant
Source: custom_components/bosch/__init__.py:366
First occurred: 2:42:58 (2 occurrences)
Last logged: 6:42:58

Error in log book
```
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/home/pi/.homeassistant/custom_components/bosch/__init__.py", line 366, in firmware_refresh
    await self.gateway.check_firmware_validity()
  File "/srv/homeassistant/lib/python3.8/site-packages/bosch_thermostat_client/gateway/base_gateway.py", line 296, in check_firmware_validity
    self._db = get_db_of_firmware(self._device[TYPE], fw)
  File "/srv/homeassistant/lib/python3.8/site-packages/bosch_thermostat_client/db/__init__.py", line 41, in get_db_of_firmware
    filename = DEVICE_TYPES[device_type].format(firmware_version.replace(".", ""))
AttributeError: 'dict' object has no attribute 'replace'
```

Trying to change the temperature I got the following error
```
Logger: bosch_thermostat_client.circuits.easycontrol.base
Source: /srv/homeassistant/lib/python3.8/site-packages/bosch_thermostat_client/circuits/easycontrol/base.py:79
First occurred: 8:51:54 (1 occurrences)
Last logged: 8:51:54

Setting temperature not allowed in this mode. Temperature is probably out of range MIN-MAX!
```
But the mobile app allows to change temperature in automatic mode too, and when the program will change the temperature later according to what is scheduled

**Comment by pszafer** [comment] 2021-04-16 07:30
> Now it works with master branch but :
> Missing base64 decoding of name `TGUgU8Opam91cg==` instead of `Le Séjour`

should be fixed in dev4. let me know.

> 
> /dhwCircuits/dhw1/operationMode could be :
> 
> * `Off` : no hot water production
> * `high` : hot water production as soon as the tank is refilled
> * `ownprogram` : automatic production mode, _economic mode_

can you switch to ownprogram and provide bosch_scan?

> 
> Error in log book
> 
> ```
> Error doing job: Task exception was never retrieved
> Traceback (most recent call last):
>   File "/home/pi/.homeassistant/custom_components/bosch/__init__.py", line 366, in firmware_refresh
>     await self.gateway.check_firmware_validity()
>   File "/srv/homeassistant/lib/python3.8/site-packages/bosch_thermostat_client/gateway/base_gateway.py", line 296, in check_firmware_validity
>     self._db = get_db_of_firmware(self._device[TYPE], fw)
>   File "/srv/homeassistant/lib/python3.8/site-packages/bosch_thermostat_client/db/__init__.py", line 41, in get_db_of_firmware
>     filename = DEVICE_TYPES[device_type].format(firmware_version.replace(".", ""))
> AttributeError: 'dict' object has no attribute 'replace'
> ```

We will get back to that later.

> 
> Trying to change the temperature I got the following error
> 
> ```
> Logger: bosch_thermostat_client.circuits.easycontrol.base
> Source: /srv/homeassistant/lib/python3.8/site-packages/bosch_thermostat_client/circuits/easycontrol/base.py:79
> First occurred: 8:51:54 (1 occurrences)
> Last logged: 8:51:54
> 
> Setting temperature not allowed in this mode. Temperature is probably out of range MIN-MAX!
> ```

I removed one `\r` from PUT maybe it will send it now.

> 
> But the mobile app allows to change temperature in automatic mode too, and when the program will change the temperature later according to what is scheduled

It's because of wrong PUT response.

**Comment by Didel** [comment] 2021-04-16 07:48
> Missing base64 decoding of name `TGUgU8Opam91cg==` instead of `Le Séjour`

Ah, I can confirm, that explains the seemingly random name I got as well. Base64 decoding it  indeed provides the correct ‘friendly name’.

**Comment by doudz** [comment] 2021-04-16 07:52
@pszafer
other things

/dhwCircuits/dhw1/temperatureLevels/high is not used on my system I think because the temperature can only be set on the heater itself by turn a button

dhwCircuits/dhw1/thermalDisinfect/time is not a duration but the hour of thermal disinfect
60mins means at 01h00 in the morning
120mins means at 02h00 in the morning

**Comment by doudz** [comment] 2021-04-16 07:54
[rawscan_101027819.zip](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/6323404/rawscan_101027819.zip)
New scan with version 0.12.0.dev4

**Comment by pszafer** [comment] 2021-04-16 08:46
> @pszafer
> other things
> 
> `/dhwCircuits/dhw1/temperatureLevels/high` is not used on my system I think because the temperature can only be set on the heater itself by turn a button

ok, so you can either don't use DHW as it's not standard... or disable it.

> 
> `/dhwCircuits/dhw1/thermalDisinfect/time` is not a duration but the hour of thermal disinfect
> 60mins means at 01h00 in the morning
> 120mins means at 02h00 in the morning

just added time sensor.

**Comment by pszafer** [comment] 2021-04-16 08:58
@doudz you switched to `ownprogram` but then `dhw` is saying it's off:
```
  {
            "id": "/dhwCircuits/dhw1/state",
            "type": "stringValue",
            "writeable": 0,
            "recordable": 0,
            "value": "off"
        },
```

**Comment by doudz** [comment] 2021-04-16 11:22
the state is `on` when the heater is heating the water, and `off` when the water temperature has been reach

**Comment by doudz** [comment] 2021-04-16 11:26
> ok, so you can either don't use DHW as it's not standard... or disable it.
> 
> >

I use DHW but the temperature can only be adjusted on the boiler, not with the application or CT200.
But I can adjust the mode : off, ownprogram, high
with ownprogram, I can't manage the program myself, the boiler do it internally (I suppose)

**Comment by pszafer** [comment] 2021-04-16 11:31
I don't understand yours setup or what they changed...
in NEFIT and IVT if there is dhw then `state/status` is always `ACTIVE` (here is `on`/`off`)

what temperature you have set on the boiler? because if it's `off` it has to read this temperature somewhere to know to turn off DHW.

@Didel can you provide your scan so we can see one more setup with DHW?

**Comment by doudz** [comment] 2021-04-16 11:48
I'll try to explain:

I have a boiler with internal tank. The boiler is used for heating the house (water radiator) and to produce hot water (dhw)
the internal tank is used for dhw, the temperature of the water is managed by the boiler
I can adjust dhw mode to disable it Off, means no more hot water (I can do that if I leave for a long time)
ownprogram is the eco mode, the boiler will heat the water at specific time, managed internally 
high : the boiler will heat the water as soon as we use it because the tank is constantly refill by cold water

the state on/off tells us if the boiler is currently heating the water or not
on the CT200 there's a red tap icon during heating

When the boiler is working for radiator, there's a red flam icon

**Comment by doudz** [comment] 2021-04-16 12:00
not sure if it's needed
new rawscan with away mode active
[rawscan_101027819.zip](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/6324722/rawscan_101027819.zip)

**Comment by Didel** [comment] 2021-04-16 12:00
> @Didel can you provide your scan so we can see one more setup with DHW?

I tried, but I guess I must be doing something wrong... I can do the scan (as instructed [here](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component#help)], I get a notification that the scan is ready, but the result is an 'empty' file:

```
[
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    []
]
```

Also, I noticed that although it does not report an error, the temperature is not being updated any more... I guess it is not working as good as I thought it was! Time to turn on some of the debugging...

**Comment by Didel** [comment] 2021-04-16 17:57
> @Didel can you provide your scan so we can see one more setup with DHW?

@pszafer I’m not sure what happened, but apparently things seem to work again (I didn’t change anything).

Does this help? (If not, which instructions should I follow?)
[bosch_scan.zip](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/6327092/bosch_scan.zip)

**Comment by doudz** [comment] 2021-04-16 18:47
Using the latest master, changing temperature is working but from time to time I still get the following error

2021-04-16 20:45:38 ERROR (MainThread) [bosch_thermostat_client.circuits.easycontrol.base] Setting temperature not allowed in this mode. Temperature is probably out of range MIN-MAX!

**Comment by doudz** [comment] 2021-04-16 19:09
@pszafer I think it could be interesting to provide climate hvac_action based on `/zones/zn1/status`

**Comment by pszafer** [comment] 2021-04-16 19:47
For setting temperature I need more info, there is something wrong in my method.
Status is read only, hvac action is more operation mode IMO as it is now

**Comment by doudz** [comment] 2021-04-16 20:51
hvac_mode is an operation mode
hvac_action is the current running operation

https://github.com/home-assistant/core/blob/dev/homeassistant/components/climate/__init__.py#L308

**Comment by pszafer** [comment] 2021-04-16 21:13
ok, I will add hvac_action.

**Comment by pszafer** [comment] 2021-04-17 11:49
- HVAC_ACTION added in master.
- more accurate logs are added for setting temperature, test it out and turn on debug logging.

**Comment by doudz** [comment] 2021-04-17 12:04
```
Error setting up entry Bosch CT200 for climate
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/config_entries.py", line 249, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/climate/__init__.py", line 162, in async_setup_entry
    return await hass.data[DOMAIN].async_setup_entry(entry)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_component.py", line 142, in async_setup_entry
    platform = await async_prepare_setup_platform(
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/setup.py", line 326, in async_prepare_setup_platform
    platform = integration.get_platform(domain)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/loader.py", line 485, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/loader.py", line 490, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pi/.homeassistant/custom_components/bosch/climate.py", line 48, in <module>
    class BoschThermostat(ClimateEntity):
  File "/home/pi/.homeassistant/custom_components/bosch/climate.py", line 173, in BoschThermostat
    def hvac_modes(self) -> list[str]:
TypeError: 'type' object is not subscriptable
```

**Comment by pszafer** [comment] 2021-04-17 13:14
> ```
> Error setting up entry Bosch CT200 for climate
> Traceback (most recent call last):
>   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/config_entries.py", line 249, in async_setup
>     result = await component.async_setup_entry(hass, self)  # type: ignore
>   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/climate/__init__.py", line 162, in async_setup_entry
>     return await hass.data[DOMAIN].async_setup_entry(entry)
>   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_component.py", line 142, in async_setup_entry
>     platform = await async_prepare_setup_platform(
>   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/setup.py", line 326, in async_prepare_setup_platform
>     platform = integration.get_platform(domain)
>   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/loader.py", line 485, in get_platform
>     cache[full_name] = self._import_platform(platform_name)
>   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/loader.py", line 490, in _import_platform
>     return importlib.import_module(f"{self.pkg_path}.{platform_name}")
>   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/home/pi/.homeassistant/custom_components/bosch/climate.py", line 48, in <module>
>     class BoschThermostat(ClimateEntity):
>   File "/home/pi/.homeassistant/custom_components/bosch/climate.py", line 173, in BoschThermostat
>     def hvac_modes(self) -> list[str]:
> TypeError: 'type' object is not subscriptable
> ```

check it now, vscode automatically added typing for me :)

**Comment by doudz** [comment] 2021-04-17 16:36
it works very well, thank you for all !

A suggestion, could you rename "heat" mode by "manual" ? Because on the app, there's 2 modes : manual and program, and on your integration, program is called auto which is ok, but manual is called heat , which is not really appropriate.
![image](https://user-images.githubusercontent.com/1262548/115119967-402f5580-9fab-11eb-90c1-8446b7cc60d4.png)

a last thing, is it possible to implement the away mode ?
on the easycontrol it's possible to enable a away mode with a specific temperature (it's also possible to enable the automatic away mode but I think we don't need this on the integration)

**Comment by doudz** [comment] 2021-04-17 16:41
Disinfect time is not display as expected, it should appears as a time, for example "01:10", not "10 hours ago"
![image](https://user-images.githubusercontent.com/1262548/115120138-22162500-9fac-11eb-884b-4e6e4387b416.png)

The same for timeToNextSetPoint

**Comment by pszafer** [comment] 2021-04-17 16:43
manual is not possible. I'm limited to hvac modes https://developers.home-assistant.io/docs/core/entity/climate#hvac-modes

for away mode, I'll try. in KM200 it was called holiday mode and it wasn't simple switch.

**Comment by Didel** [comment] 2021-04-18 11:29
I updated to the latest released version. Initially it seems to properly connect and work fine, but it looks like after the initial connection, the values aren’t updated any more. Is that a known issue?

**Comment by doudz** [comment] 2021-04-18 11:56
It works good for me, what values  aren't updated ?
![image](https://user-images.githubusercontent.com/1262548/115144600-d2883580-a04d-11eb-9f13-dacbb5a80147.png)

**Comment by Didel** [comment] 2021-04-18 12:11
The ‘climate’ entity that is being added to HomeAssistant after configuring the CT200.

At/around 22:19 I deleted the old integration and wanted to start ‘fresh’, after that it seems like no update has been received any more. The EasyControl app currently reports 22,5 degrees.

![674E9741-167E-4CD9-A159-3399B6B6989B](https://user-images.githubusercontent.com/915243/115144950-9fdf3c80-a04f-11eb-9472-d5d489b2007e.png)

**Comment by pszafer** [comment] 2021-04-18 17:56
@doudz can you check current master if sensor is better?
I think it will be better if I show you next time (in time format) than string `HH:mm` because than you can do some automation in HA if needed. in string `HH:mm` I think it will be harder.

@Didel turn on debug logging and look what's going on.

**Comment by doudz** [comment] 2021-04-18 19:09
I agree with you, and now it's better because it's the next time,
good work !

**Comment by Didel** [comment] 2021-04-19 06:43
@pszafer after another ‘remove and reset’, it again behaves the same: works fine initially, but after some time it seems to loose connection and not update any more. I found the following relevant entry in the logs:

```
Logger: custom_components.bosch
Source: custom_components/bosch/__init__.py:346
Integration: Bosch thermostat (documentation, issues) 
First occurred: 18 april 2021 23:04:47 (573 occurrences) 
Last logged: 8:38:23

Bosch object of entity Woonkamer is no longer available. Error requesting data from /programs/list
```

**Comment by pszafer** [comment] 2021-04-19 06:56
look for debug logs before last message happended (23:03:42), what happened before InvalidStateError occured.

**Comment by doudz** [comment] 2021-04-19 08:27
It's stange, the only error I still have is about firmware_version

```
Logger: homeassistant
Source: custom_components/bosch/__init__.py:377
First occurred: 0:12:49 (3 occurrences)
Last logged: 8:12:49

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/home/pi/.homeassistant/custom_components/bosch/__init__.py", line 377, in firmware_refresh
    await self.gateway.check_firmware_validity()
  File "/srv/homeassistant/lib/python3.8/site-packages/bosch_thermostat_client/gateway/base_gateway.py", line 299, in check_firmware_validity
    self._db = get_db_of_firmware(self._device[TYPE], fw)
  File "/srv/homeassistant/lib/python3.8/site-packages/bosch_thermostat_client/db/__init__.py", line 41, in get_db_of_firmware
    filename = DEVICE_TYPES[device_type].format(firmware_version.replace(".", ""))
AttributeError: 'dict' object has no attribute 'replace'
```

**Comment by doudz** [comment] 2021-04-19 18:09
Missing unit % for humidity sensor
![image](https://user-images.githubusercontent.com/1262548/115283040-2c225a00-a14b-11eb-9d8b-34bcea82d23a.png)

**Comment by Didel** [comment] 2021-04-20 21:10
> look for debug logs before last message happended (23:03:42), what happened before InvalidStateError occured.

Well, that’s the thing, there doesn’t seem to be a specific related error occurring (as far as I can tell). It looks like a restart fixes the problem temporarily, but it will at a certain point again stop updating the values.

**Comment by gralin** [comment] 2021-04-20 23:24
Hi guys! Just wanted to say thank you! Some time ago I was looking if this this CT200 thermostat can be integrated with HA but didn't find anything. Today, I had a hunch to check again and I found this repo and this thread! I instantly gave it a try and was blown away, work right on first try. I will try at least to contribute with testing, but congratulations on this! 🎊 
Attached is my debug scan, maybe it will be useful: [bosch_scan.txt](https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/files/6347122/bosch_scan.txt)

**Comment by doudz** [comment] 2021-04-21 20:58
After HA restart I got the following error :
```
Logger: aioxmpp.callbacks
Source: /srv/homeassistant/lib/python3.8/site-packages/aioxmpp/callbacks.py:536
First occurred: 21:25:04 (1 occurrences)
Last logged: 21:25:04

listener attached to signal raised
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/aioxmpp/callbacks.py", line 534, in fire
    keep = wrapper(args, kwargs)
  File "/srv/homeassistant/lib/python3.8/site-packages/aioxmpp/callbacks.py", line 468, in _strong_wrapper
    return not f(*args, **kwargs)
  File "/srv/homeassistant/lib/python3.8/site-packages/aioxmpp/dispatcher.py", line 287, in _feed
    super()._feed(stanza)
  File "/srv/homeassistant/lib/python3.8/site-packages/aioxmpp/dispatcher.py", line 135, in _feed
    cb(stanza)
  File "/srv/homeassistant/lib/python3.8/site-packages/bosch_thermostat_client/connectors/xmpp.py", line 158, in main_listener
    listener(body, http_response)
  File "/srv/homeassistant/lib/python3.8/site-packages/bosch_thermostat_client/connectors/xmpp.py", line 120, in listener
    future.set_result(recv_body)
asyncio.exceptions.InvalidStateError: invalid state
```

**Comment by doudz** [comment] 2021-04-22 11:00
@pszafer For water_heater supported features https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/blob/ba00dbaf5a0fb7063f6918b419cafa023b49aa69/custom_components/bosch/water_heater.py#L166

You should check if `/dhwCircuits/dhw1/temperatureLevels/high` is `used` , in my case it's not

```
{
            "id": "/dhwCircuits/dhw1/temperatureLevels/high",
            "type": "floatValue",
            "writeable": 1,
            "recordable": 0,
            "value": 45.0,
            "used": "false",
            "available": "false",
            "unitOfMeasure": "C",
            "minValue": 10.0,
            "maxValue": 80.0,
            "stepSize": 1.0
        },
```

**Comment by doudz** [comment] 2021-04-22 11:29
Another thing with your component
it creates many devices, a base device with no entity, sensor's devices, water heater devices, climate devices
![image](https://user-images.githubusercontent.com/1262548/115706832-5acc4a80-a36e-11eb-9321-61efda35522e.png)

but if I'm right, in HA a device is supposed to modelize a real device providing many entities or here I only have one CT200 so I think we expect to have only one device "CT200" in HA

What do you think about that ?

**Comment by pszafer** [comment] 2021-04-22 11:48
many issues stack around, for issues please open new issue so I don't miss anything.

`Missing unit % for humidity sensor` -> I copy `unitOfMeasure` from sensor, I don't know why your sensor doesn't give you %. I'll try to recreate.

`InvalidStateError` -> this is something which I will catch and I will just pass it, maybe someone with real device want to investigate what's going on, might be message be delayed, or GET request being sent and then within timeout restart of HA happened and maybe bosch xmpp is waiting for another presence of client to send response for last message.

`/dhwCircuits/dhw1/temperatureLevels/high` if it is not used then I should disable dhw in such situation?

```
it creates many devices
```

One of functions of CT200, KM200 is gateway which is bridge between your installation and xmpp server.
In your installation there are multiple devices, Zone device so some smart thermostat, HC - which are mixers for heating (don't know proper english name for it). And as I understand it is reflected in very good way, same as HA would like to have it and it is better organized that way. My inspiration was Unifi integration (unifi AP is also gateway).

**Comment by doudz** [comment] 2021-04-22 11:55
> `/dhwCircuits/dhw1/temperatureLevels/high` if it is not used then I should disable dhw in such situation?

no, you should adjust `supported_features` to `SUPPORT_OPERATION_MODE` only

**Comment by Didel** [comment] 2021-04-22 15:03
> `InvalidStateError` -> this is something which I will catch and I will just pass it, maybe someone with real device want to investigate what's going on, might be message be delayed, or GET request being sent and then within timeout restart of HA happened and maybe bosch xmpp is waiting for another presence of client to send response for last message.

@pszafer I have created #67 in order to resolve the InvalidState error.

**Comment by pszafer** [comment] 2021-04-22 18:08
@doudz `InvalidStateError` should be silent
and dhw set temperature should be disabled in your setup right now.

**Comment by doudz** [comment] 2021-04-22 19:14
> @doudz `InvalidStateError` should be silent
> and dhw set temperature should be disabled in your setup right now.

Are you sure ? because I still see `supported_features = 3`  (temperature 1 + mode 2)

![image](https://user-images.githubusercontent.com/1262548/115772579-90ddee80-a3af-11eb-843b-305973d93514.png)

**Comment by pszafer** [comment] 2021-04-22 20:15
but there is no target temp if 0 so UI shouldn't show possibility to set temperature.

**Comment by doudz** [comment] 2021-05-02 11:49
For me it works good with CT200, I think you're close to publish a new release
Thanks a lot !

**Comment by yourimmense** [comment] 2021-08-15 01:43
Hi there,

The water heater part seems to work really well although I don't have an operation mode for 'Auto' its in the bosch easycontrol app but its not in this addon. Only have Off and High Demand. Is it possible to include this?

**Comment by pszafer** [comment] 2021-08-15 19:57
@yourimmense please create new issue with bosch_scan in it while water heater is in auto mode.

**Closed by pszafer** 2021-08-15 19:57 UTC
Labels: enhancement

**Comment by oofk** [comment] 2022-09-25 11:17
Hi, 
newbie here, I've looked through all posts but cannot find the way to set a new temperature via HA automatically. 
i can set the temperature in the dashboard, but want to make it part of an automation. 

The automation I'm working on should: 
- trigger when another room is asking for heat (working)
- set temperature on ct200 to high to activate heating (not working)
- deactivate floor heating circulation pump in living room (working)

any ideas, or possibly a link to a post i've missed to be able to set temperature?

**Comment by Didel** [comment] 2022-09-25 16:47
> Hi, newbie here, I've looked through all posts but cannot find the way to set a new temperature via HA automatically. i can set the temperature in the dashboard, but want to make it part of an automation.
> 
> The automation I'm working on should:
> 
> * trigger when another room is asking for heat (working)
> * set temperature on ct200 to high to activate heating (not working)
> * deactivate floor heating circulation pump in living room (working)
> 
> any ideas, or possibly a link to a post i've missed to be able to set temperature?

You are able to do so with the `climate.set_temperature’ service, as described on https://www.home-assistant.io/integrations/climate/

**Comment by oofk** [comment] 2022-09-25 18:42
Thanks!!

Sent from my mobile device, apologies for brevity.

Op 25 sep. 2022 om 18:48 heeft Dimiter Geelen ***@***.***> het volgende geschreven:

﻿

Hi, newbie here, I've looked through all posts but cannot find the way to set a new temperature via HA automatically. i can set the temperature in the dashboard, but want to make it part of an automation.

The automation I'm working on should:

  *   trigger when another room is asking for heat (working)
  *   set temperature on ct200 to high to activate heating (not working)
  *   deactivate floor heating circulation pump in living room (working)

any ideas, or possibly a link to a post i've missed to be able to set temperature?

You are able to do so with the `climate.set_temperature’ service, as described on https://www.home-assistant.io/integrations/climate/
