### ISSUE TITLE
RuntimeWarning: coroutine 'BoschGatewayEntry.recording_sensors_update' was never awaited

### ISSUE THREAD

**Issue by slovdahl** [bosch-thermostat/home-assistant-bosch-custom-component#411] opened 2024-05-03 18:32 UTC
**Describe the bug**

After updating to HA 2024.5 I got this in the log:

```
Logger: py.warnings
Källa: util/logging.py:120
Inträffade först: 21:23:34 (1 händelser)
Senast loggade: 21:23:34

/usr/src/homeassistant/homeassistant/util/logging.py:120: RuntimeWarning: coroutine 'BoschGatewayEntry.recording_sensors_update' was never awaited log_exception(format_err, *args)
```

**To Reproduce**
1. Start HA
2. Check the log

**Expected behavior**
No warnings/errors.

**Version**
  - HA version? 2024.5.1
  - HA Bosch component version? 0.25.1
  - Python Bosch HTTP client version?

**Comment by tvc-dps** [comment] 2024-05-09 20:16
duplicate of https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/issues/409

**Closed** 2024-06-16 15:36 UTC
