### ISSUE TITLE
Integration wont load after update to HA 2024.2.2

### ISSUE THREAD

**Issue by WeirdSience** [bosch-thermostat/home-assistant-bosch-custom-component#391] opened 2024-02-17 05:51 UTC
**Describe the bug**
After updating to HA 2024.2.2 integration won´t load

**To Reproduce**
1. Go to System/Logs
2. See error message

**Expected behavior**
The integration to start

**Screenshots**

**Version**
  - 2024.2.2
  - 0.24.6
  - ?

** Debug SCAN **
** IMPORTANT **
No able to run debug scan as integration is not loaded, see error message from systems logs

**Additional context**
Logger: homeassistant.config_entries
Source: config_entries.py:444
First occurred: 06:35:37 (3 occurrences)
Last logged: 06:44:44

Error setting up entry RC300/RC310/Nefit Moduline 3000 for bosch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 444, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bosch/__init__.py", line 148, in async_setup_entry
    _init_status: bool = await gateway_entry.async_init()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bosch/__init__.py", line 245, in async_init
    if await self.async_init_bosch():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bosch/__init__.py", line 299, in async_init_bosch
    await self.gateway.check_connection()
  File "/usr/local/lib/python3.12/site-packages/bosch_thermostat_client/gateway/base.py", line 331, in check_connection
    await self.initialize()
  File "/usr/local/lib/python3.12/site-packages/bosch_thermostat_client/gateway/base.py", line 73, in initialize
    await self._update_info(initial_db.get(GATEWAY))
  File "/usr/local/lib/python3.12/site-packages/bosch_thermostat_client/gateway/ivt.py", line 75, in _update_info
    response = await self._connector.get(uri)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/bosch_thermostat_client/connectors/xmpp.py", line 94, in get
    data = await self._request(method=GET, path=path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/bosch_thermostat_client/connectors/xmpp.py", line 124, in _request
    await self.start()
  File "/usr/local/lib/python3.12/site-packages/bosch_thermostat_client/connectors/xmpp.py", line 113, in start
    self._xmppstream = await self._st.enter_async_context(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/contextlib.py", line 659, in enter_async_context
    result = await _enter(cm)
             ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aioxmpp/node.py", line 1660, in __aenter__
    await conn_future
  File "/usr/local/lib/python3.12/site-packages/aioxmpp/node.py", line 837, in _on_main_done
    task.result()
  File "/usr/local/lib/python3.12/site-packages/aioxmpp/node.py", line 1005, in _main
    await self._main_impl()
  File "/usr/local/lib/python3.12/site-packages/aioxmpp/node.py", line 951, in _main_impl
    tls_transport, xmlstream, features = await connect_xmlstream(
                                         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aioxmpp/node.py", line 390, in connect_xmlstream
    result = await _try_options(
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aioxmpp/node.py", line 241, in _try_options
    transport, xmlstream, features = await conn.connect(
                                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aioxmpp/connector.py", line 263, in connect
    await stream.starttls(
  File "/usr/local/lib/python3.12/site-packages/aioxmpp/protocol.py", line 762, in starttls
    await self._transport.starttls(ssl_context, post_handshake_callback)
  File "/usr/local/lib/python3.12/site-packages/aioopenssl/__init__.py", line 732, in starttls
    await self._waiter
  File "/usr/local/lib/python3.12/site-packages/aioopenssl/__init__.py", line 355, in _tls_do_handshake
    self._tls_conn.do_handshake()
  File "/usr/local/lib/python3.12/site-packages/OpenSSL/SSL.py", line 2202, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/lib/python3.12/site-packages/OpenSSL/SSL.py", line 1802, in _raise_ssl_error
    self._context._verify_helper.raise_if_problem()
  File "/usr/local/lib/python3.12/site-packages/OpenSSL/SSL.py", line 456, in raise_if_problem
    raise self._problems.pop(0)
  File "/usr/local/lib/python3.12/site-packages/OpenSSL/SSL.py", line 481, in wrapper
    result = callback(
             ^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aioxmpp/security_layer.py", line 300, in verify_callback
    if not check_x509_hostname(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aioxmpp/security_layer.py", line 230, in check_x509_hostname
    ssl.match_hostname(cert_structure, hostname)
    ^^^^^^^^^^^^^^^^^^
AttributeError: module 'ssl' has no attribute 'match_hostname'

**Comment by pszafer** [comment] 2024-02-17 09:02
Duplicate of https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/issues/387

**Closed by pszafer** 2024-02-17 09:02 UTC
