### ISSUE TITLE
put method on IVT/HTTP not working correctly

### ISSUE THREAD

**Issue by prj** [bosch-thermostat/home-assistant-bosch-custom-component#143] opened 2022-02-16 20:53 UTC
Hello,

There is a bug here in HTTP connector, or maybe it's upstream on command line parsing:
```
async def put(self, path, value):
    """Send message to API with given path."""
    async with self._lock:
        return await self._request(
            self._websession.put,
            path,
            data=self._encryption.encrypt(json.dumps({"value": value})),
            headers=HTTP_HEADER,
            timeout=self._request_timeout,
        )
```

You are not parsing the strings, so you are passing a string value in json to the device, and this fails. Maybe there is just too much magic, and it should just take raw json.
I added this code:
```
        try:
            value = float(value)
        except:
            pass
```

And now it was working for me correctly, because before it was passing `{"value": "52.0"}` instead of `{"value": 52.0}`.
I have MBLAN2 IVT, and I was running commands via "put" from command line.
Btw in HA this also fails, so probably not only command line is affected.

**Comment by prj** [comment] 2022-02-16 22:01
Also, I have no idea how to pass an array. Trying to write it as an array seems to fail.

**Comment by pszafer** [comment] 2022-02-17 06:13
It's definitely not a bug in this function. I can't parse every value as float because eg operation mode change is a string. 
Which function passed string instead of number? Is it service in HA?

**Comment by prj** [comment] 2022-02-17 14:35
I am talking about command line here.
If you enter something on command line it is always sent as string, but actually in IVT almost everything is a float.

**Comment by pszafer** [comment] 2022-06-29 10:10
Fixed in https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/releases/tag/v0.18.0

**Closed by pszafer** 2022-06-29 10:10 UTC
Labels: bug
